### ISSUE TITLE
Ability to download ways with missing destination tag

### ISSUE THREAD

**Issue by pratikyadav** [k1wiosm/checkautopista2#11]
Right now the tool gives us the ability to download ways which already have `destination` tag, but not for the one missing them.

Most exit number have a corresponding `destination` sign. Thus it would be nice to have the feature to download the motorway/motorway_link going out of a mapped exit number.

![screen shot 2016-04-26 at 12 51 45 pm](https://cloud.githubusercontent.com/assets/12744420/14809885/ab4b190e-0bad-11e6-95b7-e40e6c0b8054.png)

In simple words: if the inner circle is green and the outer circle is red, a link to download way going out of `motorway_junction`.

@k1wiosm thoughts?

**Comment by k1wiosm** [comment]
You are right.

Now the tool will download the `motorway_link` of all `motorway_junction`s.

https://github.com/k1wiosm/checkautopista2/commit/a80cfb738cfff1026a41fb8e5f4e27be9c395452

**Comment by pratikyadav** [comment]
This is great @k1wiosm 

Thanks for adding this feature.
