### ISSUE TITLE
Mixed Content warning

### ISSUE THREAD

**Issue by Caboosey** [k1wiosm/checkautopista2#12]
When opening https://k1wiosm.github.io/checkautopista2/ with Mapillary layer turned on. Browsers block and report mixed content warning (Attempted to load HTTP content on a HTTPS requested page)

Example Errors from Console of browser:

> Mixed Content: The page at 'https://k1wiosm.github.io/checkautopista2/?lat=30.6226&lon=-87.3317&z=10' was loaded over HTTPS, but requested an insecure resource 'http://d2munx5tg0hw47.cloudfront.net/tiles/10/263/421.mapbox'. This request has been blocked; the content must be served over HTTPS._getVectorTilePromise @ Leaflet.VectorGrid.bundled.js:2765createTile @ Leaflet.VectorGrid.bundled.js:2555_addTile @ leaflet.js:6_update @ leaflet.js:6_setView @ leaflet.js:6_resetView @ leaflet.js:6onAdd @ leaflet.js:6_layerAdd @ leaflet.js:6whenReady @ leaflet.js:6addLayer @ leaflet.js:6showTiles @ main.js:180updateTiles @ main.js:159(anonymous function) @ main.js:40
> Leaflet.VectorGrid.bundled.js:2765Fetch API cannot load http://d2munx5tg0hw47.cloudfront.net/tiles/10/263/421.mapbox. Failed to start loading._getVectorTilePromise @ Leaflet.VectorGrid.bundled.js:2765createTile @ Leaflet.VectorGrid.bundled.js:2555_addTile @ leaflet.js:6_update @ leaflet.js:6_setView @ leaflet.js:6_resetView @ leaflet.js:6onAdd @ leaflet.js:6_layerAdd @ leaflet.js:6whenReady @ leaflet.js:6addLayer @ leaflet.js:6showTiles @ main.js:180updateTiles @ main.js:159(anonymous function) @ main.js:40
> Leaflet.VectorGrid.bundled.js:2765Mixed Content: The page at 'https://k1wiosm.github.io/checkautopista2/?lat=30.6226&lon=-87.3317&z=10' was loaded over HTTPS, but requested an insecure resource 'http://d2munx5tg0hw47.cloudfront.net/tiles/10/262/419.mapbox'. This request has been blocked; the content must be served over HTTPS.

**Comment by k1wiosm** [comment]
Fixed. 

@Caboosey and @51114u9, thanks!
