### ISSUE TITLE
FL 293 Toll isn't recognized

### ISSUE THREAD

**Issue by Caboosey** [k1wiosm/checkautopista2#14]
Part of FL 293 Toll is a motorway and checkautopista2 fails to recognize it in the "Search in map" feature.

FL 293 Toll is located near Niceville, Florida, United States.

https://www.openstreetmap.org/relation/382653

**Comment by k1wiosm** [comment]
When checkautopista2 is searching for motorway relations, it only downloads one way from each relation and checks if it is a `highway=motorway`. It only downloads one single way to prevent downloading too much data when searching for motorways and make it faster.

Looks like it found a `highway=trunk` when checking FL 293 Toll, so it doesn't show it.

As a workaround you can download any relation using the _Get by relation ID_ or directly: http://k1wiosm.github.io/checkautopista2/?id=382653

**Comment by Caboosey** [comment]
@k1wiosm This route is a mix of highway=motorway and highway=trunk. Most of the route is a highway=trunk and this section here is highway=motorway https://www.openstreetmap.org/#map=14/30.4738/-86.4041

In future plans by FL DOT, they plan to make it a motorway all the way to FL 85.
