### ISSUE TITLE
Split Exits Info aren't shown

### ISSUE THREAD

**Issue by Caboosey** [k1wiosm/checkautopista2#15]
I noticed when freeways/motorways have a split exit. checkautopista2 only shows one of the exits sign info and not both.

Example: I-165 (Northbound) terminated at I-65 in Mobile, Alabama, United States

Exit 1A
I-10
Mobile

Exit 1B
I-10
Montgomery

Mapillary photo: https://www.mapillary.com/map/im/r4p1DzUD7qyq-t-gewdwVw/photo
![2016-07-16_01](https://cloud.githubusercontent.com/assets/12619646/16895622/98ef4c06-4b42-11e6-9b8e-ae638f7e7ec2.jpg)

http://k1wiosm.github.io/checkautopista2/?id=1693963&lat=30.7511&lon=-88.0957&z=16

**Comment by k1wiosm** [comment]
Thank you for the suggestion!

It should be working now (https://github.com/k1wiosm/checkautopista2/commit/57840c67389b182670694a3618eff7c496dbe640). 

![](https://cloud.githubusercontent.com/assets/8932566/16897437/d2a4df82-4bb1-11e6-8f92-97782727fde7.png)

**Comment by Caboosey** [comment]
Thank you @k1wiosm. It looks great. :+1:
