### ISSUE TITLE
Destination:symbol to show symbols

### ISSUE THREAD

**Issue by Caboosey** [k1wiosm/checkautopista2#17]
Issue type: Feature Request

For US based signs, can you show info signs just above the Exit Info sign that is shown:
![2016-07-18_01](https://cloud.githubusercontent.com/assets/12619646/16908494/b3aaed3e-4c91-11e6-9d99-a0cbdb4cbe97.jpg)
http://k1wiosm.github.io/checkautopista2/?id=1024908&lat=30.5029&lon=-87.2186&z=15

European symbol signs are shown on the wiki page:
https://wiki.openstreetmap.org/wiki/Proposed_features/Destination_details

Here is ones currently used in the United States. The ones without aren't used in US.

destination:symbol=airport
https://upload.wikimedia.org/wikipedia/commons/b/bf/MUTCD_I-5.svg

destination:symbol=centre

destination:symbol=harbour

destination:symbol=hospital
https://upload.wikimedia.org/wikipedia/commons/f/fd/MUTCD_D9-2.svg

destination:symbol=railroad_freight_terminal

destination:symbol=train_station
https://upload.wikimedia.org/wikipedia/commons/a/a5/MUTCD_I-7.svg

destination:symbol=interchange

destination:symbol=food
https://upload.wikimedia.org/wikipedia/commons/9/9d/MUTCD_D9-8.svg

destination:symbol=fuel
https://upload.wikimedia.org/wikipedia/commons/0/03/MUTCD_D9-7.svg

destination:symbol=lodging
https://upload.wikimedia.org/wikipedia/commons/4/44/MUTCD_D9-9.svg

destination:symbol=parking
https://upload.wikimedia.org/wikipedia/commons/c/cb/Japanese_Road_sign_(Parking_lot_A,_Parking_permitted).svg

destination:symbol=covered_parking

destination:symbol=park_and_ride

destination:symbol=industrial

destination:symbol=motorway

destination:symbol=camp_site
https://upload.wikimedia.org/wikipedia/commons/4/45/MUTCD_D9-3.svg

destination:symbol=ferry
https://upload.wikimedia.org/wikipedia/commons/7/72/MUTCD_I-9.svg

destination:symbol=soccer_stadium

destination:symbol=stadium

**Comment by k1wiosm** [comment]
Will do it

**Comment by k1wiosm** [comment]
I added some basic support for destination:symbol on https://github.com/k1wiosm/checkautopista2/commit/25c0a80a422b93460744e9dcc16c7f7db0911f86.

Still working on it.

**Comment by Caboosey** [comment]
Looks good so far @k1wiosm 

Great work!

![2016-07-28_01](https://cloud.githubusercontent.com/assets/12619646/17220932/20937290-54b7-11e6-8f75-51f0b02cce8b.jpg)

**Comment by k1wiosm** [comment]
On european style I am showing the symbols inside the sign. Also I created a symbol for unknown values.

![](https://cloud.githubusercontent.com/assets/8932566/17272449/ccabe996-5696-11e6-958c-45071666555c.png)

**Comment by k1wiosm** [comment]
I added support for different US & EU symbols (https://github.com/k1wiosm/checkautopista2/commit/3c0ef16076e22a7da6a80a0bb441db49c2c97f78).

I think that with these last improvements it's done. 

@Caboosey what do you think?

**Comment by Caboosey** [comment]
@k1wiosm Looks great! :)

The ? image be confusing though. That is used in the US for "Info" sometimes.

**Comment by Caboosey** [comment]
Oh yes. LOL. That is a good one. :)

That should make someone be like I need to check this exit info out.
