### ISSUE TITLE
weird pink and black circles visible after disabling everything

### ISSUE THREAD

**Issue by matkoniecz** [k1wiosm/checkautopista2#2]
to reproduce: go to http://k1wiosm.github.io/checkautopista/?id=114014&lat=51.2516&lon=20.0171&z=7

disable all displayed features (BTW, maybe permalinks would be a good idea?)

still some pink and black circles are displayed

![selection_002](https://cloud.githubusercontent.com/assets/899988/9530001/b091c364-4cfd-11e5-966f-0c0b85a3e6f4.png)

**Comment by k1wiosm** [comment]
That is really weird. I'll have a look into that.

**Comment by k1wiosm** [comment]
The problem was that it was adding some circles twice and was only hiding one of them.
