### ISSUE TITLE
Fails to display exit info on proposed/construction exits

### ISSUE THREAD

**Issue by Caboosey** [k1wiosm/checkautopista2#23]
I noticed that currently checkautopista fails to shows exit info when exit ramps are under construction or proposed.

Here is example in Montgomery, AL, US:
https://k1wiosm.github.io/checkautopista2/?id=5941009&lat=32.3366&lon=-86.0626&z=15
![2016-08-05_01](https://cloud.githubusercontent.com/assets/12619646/17453945/98b46f40-5b4c-11e6-84bc-35a5f0ffcf8d.jpg)
![2016-08-05_02](https://cloud.githubusercontent.com/assets/12619646/17453951/ad33be6c-5b4c-11e6-8c28-9a85b6f0530a.jpg)

**Comment by k1wiosm** [comment]
Done
