### ISSUE TITLE
Allow to jump to next/previous way or node

### ISSUE THREAD

**Issue by claudiush** [k1wiosm/checkautopista2#25]
Check Autopista is a great tool to maintain a high quality for motorways in OpenStreetMap. Most common use case is probably to review existing routes for errors. I find myself dragging the map along the route to find the next exit or untagged way to review.

Suggestion:
Add a "Next" / "Previous" link to the element infobox on the left. This is probably a bit easier for ways which have a direction than for exits, but either would be really beneficial.

Something to keep in mind is that depending on the tagging there might be more than 2 ways in the route that are connected to each way. so maybe instead of buttons a list of connecting ways on start and end of each way would scale better interaction wise. Here's a rough mockup of what i think of:
![autopista_next_prev_links_mockup](https://cloud.githubusercontent.com/assets/428616/22075491/11823aae-dda4-11e6-9a1b-ec7c9557ca71.png)

**Comment by k1wiosm** [comment]
That is a great idea 👍. I will do it.

**Comment by k1wiosm** [comment]
It should be working right now. I added previous/next links to both ways and exit nodes. You can also use the shortcuts k/j to navigate. 

Let me know what you think! There might some bugs so if you find any please report them.
