### ISSUE TITLE
Page causes very high load and sometimes crashing Chrom

### ISSUE THREAD

**Issue by claudiush** [k1wiosm/checkautopista2#27]
When loading the relation 2895602 for a road in Lithuania the page is freezing indefinitely with the loader animation showing in the left navigation tabs:
http://k1wiosm.github.io/checkautopista2/?id=2895602&lat=55.8815&lon=23.4489&z=13

Couldn't figure out yet what causes this as the developer tools output isn't helpful either. The download seems to finish, but then while processing the data something goes awfully wrong.

**Comment by k1wiosm** [comment]
Must be something related to the processing done to obtain the previous/next way or exit (gh-25).

I'll look into it.

**Comment by k1wiosm** [comment]
There was a bug in the next exit search algorithm. I fixed it.

Similar bugs or some weird geometries of the motorways can cause the algorithm to become stuck and crash the browser. To prevent this I added a timeout.
