### ISSUE TITLE
Add advisory speed limit signs

### ISSUE THREAD

**Issue by micahcochran** [k1wiosm/checkautopista2#28]
The visual aspect that that you are tagging this to compose what is on the signs really resonates with me and made me want to improve the interstate tagging in my local area.

My suggestion is to add [advisory speed limit signs](https://en.wikipedia.org/wiki/Advisory_speed_limit) for exit ramps.  Which tagged by [maxspeed:advisory](http://wiki.openstreetmap.org/wiki/Key:maxspeed:advisory)=*.   This is a feature request.

I do realize that there are different signs used in different countries.  There are units to contend with MPH for US and UK.  km/h for everywhere else.  

The US version (W13-2) , which it looks like *might* be modified to create something similar for other countries.
![116px-mutcd_w13-2 svg](https://cloud.githubusercontent.com/assets/7433104/22270028/7d60bd28-e253-11e6-83c2-c9794842443e.png)

It looks like the most of the EU could use the blue sign.
![145px-zeichen_380-52_-_richtgeschwindigkeit_80_km-h _stvo_1992 svg](https://cloud.githubusercontent.com/assets/7433104/22269922/03e30a3c-e253-11e6-9d73-3db20d8c5cf6.png)

I think that this would be put at the top with the [destination:symbols](http://wiki.openstreetmap.org/wiki/Proposed_features/Destination_details), using a similar scale as those symbols.  The advisory speed limit is good information, but this not as important as the green guide sign with the exit number.

**Comment by k1wiosm** [comment]
Thanks for the suggestion.

Are advisory speed limits indicated on the same panel as the freeway exit information? Do you have any photo (street view, mapillary) where I can see them in the wild?

**Comment by micahcochran** [comment]
No, it is a separate sign that generally appears at the beginning of the exit or just before the point of turning.  You'd see the green guide exit sign before you'd see this.  Most interstate exits in Alabama, USA will have this sign, even the gradual exits have this sign.

Here are some examples:
* I-565 west bound Exit 7 County Line Road - [Google Streetview](https://www.google.com/maps/@34.6609641,-86.7888101,3a,75y,273.72h,74.49t/data=!3m6!1e1!3m4!1s4ebIf6JOt7NNK1pmKv-IEw!2e0!7i13312!8i6656),  [OSM Way: 332475799](https://www.openstreetmap.org/way/332475799) -- this one has a sharp turn to it
* I-65 north bound Exit 351 Athens US Highway 72  - [Google Streetview](https://www.google.com/maps/@34.7795504,-86.9396948,3a,75y,19.2h,72.3t/data=!3m7!1e1!3m5!1s-dAdDc7ZY9uDKkNvD1DDoQ!2e0!6s%2F%2Fgeo1.ggpht.com%2Fcbk%3Fpanoid%3D-dAdDc7ZY9uDKkNvD1DDoQ%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D118.79558%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656!4m5!3m4!1s0x888911df5885bfd3:0x25507409eaba54ce!8m2!3d33.5207891!4d-86.8026352!6m1!1e1), [OSM Way: 7790095](https://www.openstreetmap.org/way/7790095) -- this one is gradual
* I-85 northbound Exit 45B at W.T. Harris Blvd (State Route 24)- [Google Streetview](https://www.google.com/maps/@35.312032,-80.7583396,3a,75y,43.73h,75.63t/data=!3m6!1e1!3m4!1sfcMnpWYr1yyddO9MNVk7Ww!2e0!7i13312!8i6656),   [OSM](https://www.openstreetmap.org/#map=18/35.31200/-80.75843)   -  I've not edited OSM for this one.

**Comment by k1wiosm** [comment]
I added the `maxspeed:advisory` signs. Let me know what you think.

US: http://k1wiosm.github.io/checkautopista2/?id=132290&lat=34.2036&lon=-86.8783&z=15
EU: http://k1wiosm.github.io/checkautopista2/?id=75144&lat=51.4332&lon=4.2836&z=15

![](https://cloud.githubusercontent.com/assets/8932566/22432137/36a53fa6-e714-11e6-90cb-254867e5e03a.png)

**Comment by micahcochran** [comment]
That looks great.  Thanks for implementing this so quickly.
