### ISSUE TITLE
Show highway=toll_gantry

### ISSUE THREAD

**Issue by goldfndr** [k1wiosm/checkautopista2#34]
[highway=toll_gantry](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtoll_gantry)

This would presumably be shown identical to barrier=toll_booth, as I'm guessing most motorways wouldn't have both.

**Comment by andrewharvey** [comment]
proposed fix in #37

**Comment by k1wiosm** [comment]
@andrewharvey Thank you so much for your pull request!
