### ISSUE TITLE
Ability to search for a motorway by ref/name

### ISSUE THREAD

**Issue by baditaflorin** [k1wiosm/checkautopista2#5]
It would be nice if i want to search for a motorway, by searching it`s name, ref or network ...

I did not studied the source could to see how you do the overpass query, i will when i will have time, but until then, i wanted to leave this suggestion here

**Comment by k1wiosm** [comment]
Working on it.

**Comment by k1wiosm** [comment]
Done. 
653b4eb5ea98ce7919808863e4ad5f41a6e3879b
046375ac42f8ed343309b8d121c5844c2a09fc38
3c2c00689c88b2c3cb71b02535dd6bffef3677e2
01a2468a7b68acae76f54bcc7b104095d3d3b651
57f31f65a1a6e7b0ec4f1ebeaefa79c67140d6f3
3262a8d698d702d1aa7910d572d7c7a645c5e1ee
f1918e2d62dd6b76847cc576fb773dd47d270259
