### ISSUE TITLE
Adding a different color for motorway_junction with noref=yes

### ISSUE THREAD

**Issue by pratikyadav** [k1wiosm/checkautopista2#8]
Right now the `highway=motorway_junction` with `noref=yes` apperas as same as missing exit numbers. 

![screen shot 2016-04-05 at 4 28 01 pm](https://cloud.githubusercontent.com/assets/12744420/14279550/65df52c6-fb4b-11e5-9dfd-a72845e59952.png)

`noref=yes` is used in case where there is no associated exit number for the `motorway_junction`

Would be nice to have a separate color for this.

https://taginfo.openstreetmap.org/keys/noref#map

**Comment by k1wiosm** [comment]
Thanks for the great idea! I will do it.

**Comment by k1wiosm** [comment]
It should be good now. Added on https://github.com/k1wiosm/checkautopista2/commit/ba0fe877bd1f58cc0d729c1e0d8f71bc29d533d1.

**Comment by pratikyadav** [comment]
@k1wiosm this is great 🚀 
Thanks.

![screen shot 2016-04-07 at 3 12 56 pm](https://cloud.githubusercontent.com/assets/12744420/14347163/3e901104-fcd3-11e5-9cd9-b63db573fa40.png)
