### ISSUE TITLE
Freeway Exits Not Consistently Displayed

### ISSUE THREAD

**Issue by Zian** [k1wiosm/checkautopista2#9]
To observe the issue, go to http://k1wiosm.github.io/checkautopista2/?id=1404728&lat=39.6126&lon=-79.9211&z=17 and click on exit 4. You will see a blue bit of signage in the upper left that looks like this:
_________________4
Sabraton______[WV-7]

Now, go to http://k1wiosm.github.io/checkautopista2/?id=2297473&lat=33.0450&lon=-117.2784&z=15 and click on exit 41A. You will see this:
________________41A

In both cases, the node is tagged as highway=motorway_junction and the ramp is a highway=motorway_link. They both have ref tags on the nodes and ways.

In addition to the difference in the blue signs, the Sabraton example appears as a node with a green border but the 41A example has a red border.

I would expect the 41A example to show up the same way as the Sabraton example with some sort of minor difference to indicate that "Encinitas Boulevard" is the destination:street of the freeway offramp.

**Comment by Zian** [comment]
![comparison](https://cloud.githubusercontent.com/assets/1581929/14776989/e3517274-0a7e-11e6-8454-9631f230a26c.png)

**Comment by k1wiosm** [comment]
The tool is now showing the motorway_link way tags below (#11).

I will add destination:street information to the blue sign too. 

I believe `destination:street` is used in America. Any suggestions for the style in the blue sign?

**Comment by k1wiosm** [comment]
Added support for `destination:street` on https://github.com/k1wiosm/checkautopista2/commit/9ce0cc872e5a23403a210fb7dc8dc7da8c360044. I didn't do anything special to indicate that it is a different tag. If you have any suggestion on the styling I would be glad to hear them.
